// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {daedalus} from '../models';
import {main} from '../models';

export function CreateCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<daedalus.KanbanCard>;

export function DeleteCard(arg1:string):Promise<void>;

export function GetCardContent(arg1:string):Promise<string>;

export function GetMetrics():Promise<main.AppMetrics>;

export function LoadBoard(arg1:string):Promise<main.BoardResponse>;

export function MoveCard(arg1:string,arg2:string,arg3:number):Promise<daedalus.KanbanCard>;

export function OpenFileExternal(arg1:string):Promise<void>;

export function SaveCard(arg1:string,arg2:daedalus.CardMetadata,arg3:string):Promise<daedalus.KanbanCard>;

export function SaveCollapsedLists(arg1:Array<string>):Promise<void>;

export function SaveLabelsExpanded(arg1:boolean):Promise<void>;

export function SaveListConfig(arg1:string,arg2:string,arg3:number):Promise<void>;
