// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCard'](arg1, arg2, arg3, arg4);
}

export function CreateList(arg1) {
  return window['go']['main']['App']['CreateList'](arg1);
}

export function DeleteAllCards(arg1) {
  return window['go']['main']['App']['DeleteAllCards'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['main']['App']['DeleteCard'](arg1);
}

export function DeleteIcon(arg1) {
  return window['go']['main']['App']['DeleteIcon'](arg1);
}

export function DeleteList(arg1) {
  return window['go']['main']['App']['DeleteList'](arg1);
}

export function GetCardContent(arg1) {
  return window['go']['main']['App']['GetCardContent'](arg1);
}

export function GetIconContent(arg1) {
  return window['go']['main']['App']['GetIconContent'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetScratchpad() {
  return window['go']['main']['App']['GetScratchpad']();
}

export function ListIcons() {
  return window['go']['main']['App']['ListIcons']();
}

export function LoadBoard(arg1) {
  return window['go']['main']['App']['LoadBoard'](arg1);
}

export function MoveAllCards(arg1, arg2) {
  return window['go']['main']['App']['MoveAllCards'](arg1, arg2);
}

export function MoveCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveCard'](arg1, arg2, arg3);
}

export function OpenFileExternal(arg1) {
  return window['go']['main']['App']['OpenFileExternal'](arg1);
}

export function OpenURI(arg1) {
  return window['go']['main']['App']['OpenURI'](arg1);
}

export function RemoveLabel(arg1) {
  return window['go']['main']['App']['RemoveLabel'](arg1);
}

export function RenameLabel(arg1, arg2) {
  return window['go']['main']['App']['RenameLabel'](arg1, arg2);
}

export function SaveBoardTitle(arg1) {
  return window['go']['main']['App']['SaveBoardTitle'](arg1);
}

export function SaveCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCard'](arg1, arg2, arg3);
}

export function SaveCollapsedLists(arg1) {
  return window['go']['main']['App']['SaveCollapsedLists'](arg1);
}

export function SaveCustomIcon(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomIcon'](arg1, arg2);
}

export function SaveDarkMode(arg1) {
  return window['go']['main']['App']['SaveDarkMode'](arg1);
}

export function SaveHalfCollapsedLists(arg1) {
  return window['go']['main']['App']['SaveHalfCollapsedLists'](arg1);
}

export function SaveLabelColors(arg1) {
  return window['go']['main']['App']['SaveLabelColors'](arg1);
}

export function SaveLabelsExpanded(arg1) {
  return window['go']['main']['App']['SaveLabelsExpanded'](arg1);
}

export function SaveListConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveListConfig'](arg1, arg2, arg3, arg4);
}

export function SaveListOrder(arg1) {
  return window['go']['main']['App']['SaveListOrder'](arg1);
}

export function SaveLockedLists(arg1) {
  return window['go']['main']['App']['SaveLockedLists'](arg1);
}

export function SaveMinimalView(arg1) {
  return window['go']['main']['App']['SaveMinimalView'](arg1);
}

export function SavePinnedLists(arg1, arg2) {
  return window['go']['main']['App']['SavePinnedLists'](arg1, arg2);
}

export function SaveScratchpad(arg1) {
  return window['go']['main']['App']['SaveScratchpad'](arg1);
}

export function SaveShowYearProgress(arg1) {
  return window['go']['main']['App']['SaveShowYearProgress'](arg1);
}

export function SaveZoom(arg1) {
  return window['go']['main']['App']['SaveZoom'](arg1);
}
