// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {daedalus} from '../models';
import {main} from '../models';

export function CreateCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<daedalus.KanbanCard>;

export function CreateList(arg1:string):Promise<void>;

export function DeleteAllCards(arg1:string):Promise<void>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteIcon(arg1:string):Promise<void>;

export function DeleteList(arg1:string):Promise<void>;

export function ExportJSON(arg1:string):Promise<void>;

export function ExportZip(arg1:string):Promise<void>;

export function GetAppConfig():Promise<daedalus.AppConfig>;

export function GetCardContent(arg1:string):Promise<string>;

export function GetIconContent(arg1:string):Promise<string>;

export function GetMetrics():Promise<main.AppMetrics>;

export function GetScratchpad():Promise<string>;

export function GetVersion():Promise<string>;

export function ListIcons():Promise<Array<string>>;

export function LoadBoard(arg1:string):Promise<main.BoardResponse>;

export function MoveAllCards(arg1:string,arg2:string):Promise<void>;

export function MoveCard(arg1:string,arg2:string,arg3:number):Promise<daedalus.KanbanCard>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileExternal(arg1:string):Promise<void>;

export function OpenURI(arg1:string):Promise<void>;

export function RemoveLabel(arg1:string):Promise<void>;

export function RemoveRecentBoard(arg1:string):Promise<void>;

export function RenameLabel(arg1:string,arg2:string):Promise<void>;

export function SaveBoardTitle(arg1:string):Promise<void>;

export function SaveCard(arg1:string,arg2:daedalus.CardMetadata,arg3:string):Promise<daedalus.KanbanCard>;

export function SaveCollapsedLists(arg1:Array<string>):Promise<void>;

export function SaveCustomIcon(arg1:string,arg2:string):Promise<void>;

export function SaveDarkMode(arg1:boolean):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveHalfCollapsedLists(arg1:Array<string>):Promise<void>;

export function SaveLabelColors(arg1:Record<string, string>):Promise<void>;

export function SaveLabelsExpanded(arg1:boolean):Promise<void>;

export function SaveListConfig(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<void>;

export function SaveListOrder(arg1:Array<string>):Promise<void>;

export function SaveLockedLists(arg1:Array<string>):Promise<void>;

export function SaveMinimalView(arg1:boolean):Promise<void>;

export function SavePinnedLists(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function SaveScratchpad(arg1:string):Promise<void>;

export function SaveShowYearProgress(arg1:boolean):Promise<void>;

export function SaveTemplates(arg1:Array<daedalus.CardTemplate>):Promise<void>;

export function SaveZoom(arg1:number):Promise<void>;

export function SetDefaultBoard(arg1:string):Promise<void>;
