// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCardContent(arg1:string):Promise<string>;

export function GetMetrics():Promise<main.AppMetrics>;

export function LoadBoard(arg1:string):Promise<main.BoardResponse>;

export function SaveListConfig(arg1:string,arg2:string,arg3:number):Promise<void>;
