// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCardContent(arg1) {
  return window['go']['main']['App']['GetCardContent'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function LoadBoard(arg1) {
  return window['go']['main']['App']['LoadBoard'](arg1);
}
